compiler:
  solc:
    remappings:
      - "@upopenzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.5.0

